# Site settings
title: "Currículo de Lucas Cabral"
description: "Formação e experiência profissional do jornalista Lucas Cabral."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lucas S. C. Cabral"
resume_title:                   "Jornalista e mestre em jornalismo"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "eu@lucascabral.net"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "sem número"
resume_contact_address:         "Sem endereço"

resume_header_contact_info:     "eu@lucascabral.net"
display_header_contact_info:    "false"

resume_header_intro: "<p>Sou jornalista formado pela Universidade Estadual de Ponta Grossa, mestre pela mesma instituição. Durante o mestrado, fui bolsista da Coordenação de Aperfeiçoamento de Pessoal de Nível Superior e desenvolvi pesquisa sobre a reportagem jornalística na internet em um contexto de crise do jornalismo. Tenho experiência com reportagem, redação, fotografia, edição de fotos e vídeos,  diagramação, programação, desenvolvimento e manutenção de sites, editoração de periódicos acadêmicos, organização de eventos, entre outras atividades. Tenho interesse em vagas para jornalista, professor de jornalismo, assessor de imprensa e/ou redator.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/luscacabral"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/lucas-s-c-cabral/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://lucascabral.net"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
